FROM fedora@sha256:36af84ba69e21c9ef86a0424a090674c433b2b80c2462e57503886f1d823abe8 as build

RUN dnf -y update && \
    dnf -y install @development-tools pkg-config iproute iputils wget git jq openssl-devel cryptsetup-libs cryptsetup-devel && \
    dnf clean all

# Install Go
ARG GO_VER=1.18
RUN wget https://go.dev/dl/go${GO_VER}.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go${GO_VER}.linux-amd64.tar.gz && \
    rm go${GO_VER}.linux-amd64.tar.gz
ENV PATH ${PATH}:/usr/local/go/bin

# Download go dependencies
WORKDIR /constellation/
COPY go.mod ./
COPY go.sum ./
COPY go.work ./
COPY go.work.sum ./
COPY hack/go.mod ./hack/go.mod
COPY hack/go.sum ./hack/go.sum
RUN go mod download all

# Copy Repo
COPY . /constellation

FROM build AS build-coordinator
WORKDIR /constellation/coordinator/

ARG PROJECT_VERSION
RUN go build -o coordinator -tags=gcp,disable_tpm_simulator -buildvcs=false -ldflags "-s -w -buildid='' -X main.version=${PROJECT_VERSION}" ./cmd/coordinator/

FROM build-coordinator AS hash-coordinator
RUN mv coordinator coordinator-$(sha512sum coordinator | cut -d " " -f 1)

FROM build AS build-disk-mapper
WORKDIR /constellation/state/

RUN go build -o disk-mapper -ldflags "-s -w" ./cmd/

FROM scratch AS coordinator
COPY --from=build-coordinator /constellation/coordinator/coordinator /

FROM scratch AS coordinator-hashed
COPY --from=hash-coordinator /constellation/coordinator/coordinator-* /

FROM scratch AS disk-mapper
COPY --from=build-disk-mapper /constellation/state/disk-mapper /
