# This content is generated by {GENERATOR}
load("@constellation//bazel/mkosi:toolchain.bzl", "mkosi_toolchain")

mkosi_toolchain(
    name = "mkosi_auto",
    path = "{MKOSI_PATH}",
)

toolchain(
    name = "mkosi_auto_toolchain",
    toolchain = ":mkosi_auto",
    toolchain_type = "@constellation//bazel/mkosi:toolchain_type",
)
