[Output]
KernelCommandLine=constel.csp=azure
OutputDirectory=mkosi.output.azure

# replace kernel
[Content]
BasePackages=conditional
Packages=systemd
         util-linux
         dracut
         kernel
         kernel-core
         kernel-headers
         kernel-devel
         bpftool
         bcc
         bcc-tools
         bcc-devel
         binutils
         ncurses
         coreutils
         wget
         git
