// Code generated by "stringer -type=Role"; DO NOT EDIT.

package role

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[ControlPlane-1]
	_ = x[Worker-2]
}

const _Role_name = "UnknownControlPlaneWorker"

var _Role_index = [...]uint8{0, 7, 19, 25}

func (i Role) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Role_index)-1 {
		return "Role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Role_name[_Role_index[idx]:_Role_index[idx+1]]
}
