// Code generated by "stringer -type=EnforceIDKeyDigest"; DO NOT EDIT.

package idkeydigest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[StrictChecking-1]
	_ = x[MAAFallback-2]
	_ = x[WarnOnly-3]
}

const _EnforceIDKeyDigest_name = "UnknownStrictCheckingMAAFallbackWarnOnly"

var _EnforceIDKeyDigest_index = [...]uint8{0, 7, 21, 32, 40}

func (i EnforceIDKeyDigest) String() string {
	if i >= EnforceIDKeyDigest(len(_EnforceIDKeyDigest_index)-1) {
		return "EnforceIDKeyDigest(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnforceIDKeyDigest_name[_EnforceIDKeyDigest_index[i]:_EnforceIDKeyDigest_index[i+1]]
}
