name: Constellation recover
description: "Recover a Constellation cluster with an unavailable control plane."

inputs:
  kubeconfig:
    description: "The kubeconfig for the cluster."
    required: true
  masterSecret:
    description: "The master-secret for the cluster."
    required: true
  cloudProvider:
    description: "Which cloud provider to use."
    required: true
  gcpProject:
    description: "The GCP project Constellation is deployed in."
    required: false
  resourceGroup:
    description: "The Azure resource group Constellation is deployed in."
    required: false

runs:
  using: "composite"
  steps:
    # Restart worker node machine and wait for it to rejoin the cluster
    - name: Restart worker node
      shell: bash
      run: |
        WORKER_NODE=$(kubectl get nodes --selector='!node-role.kubernetes.io/control-plane' -o json | jq '.items[0].metadata.name' -r)
        kubectl debug node/$WORKER_NODE --image=ubuntu -- bash -c "echo reboot > temp.txt && chroot /host < temp.txt"
        kubectl wait --for=condition=Ready=false --timeout=10m node/$WORKER_NODE
        kubectl wait --for=condition=Ready=true --timeout=10m --all nodes
      env:
        KUBECONFIG: ${{ inputs.kubeconfig }}
    # Restart control plane machines
    - name: Restart control plane on GCP
      if: ${{ inputs.cloudProvider == 'gcp' }}
      shell: bash
      run: |
        CONTROL_PLANE_NODES=$(kubectl get nodes --selector='node-role.kubernetes.io/control-plane' -o json | jq '.items[].metadata.name' -r)
        for CONTROL_PLANE_NODE in ${CONTROL_PLANE_NODES}
        do
        kubectl debug node/$CONTROL_PLANE_NODE --image=ubuntu -- bash -c "echo reboot > temp.txt && chroot /host < temp.txt"
        done
    # Recover the control plane
    - name: Constellation recover
      run: |
        constellation recover --master-secret=${{ inputs.masterSecret }}
        kubectl wait --for=condition=Ready --timeout=10m --all nodes
      shell: bash
      env:
        KUBECONFIG: ${{ inputs.kubeconfig }}
