# syntax=docker/dockerfile:1.5-labs
FROM alpine:3.17.3@sha256:b6ca290b6b4cdcca5b3db3ffa338ee0285c11744b4a6abaa9627746ee3291d8d as builder

ADD --checksum=sha256:11968a8b706095a081ac30168849b351b0263a6df5c224119aa914d7e5afb0c1 \
    https://github.com/reproducible-containers/repro-get/releases/download/v0.3.0/repro-get-v0.3.0.linux-amd64 \
    /usr/bin/repro-get
RUN chmod +x /usr/bin/repro-get

RUN apk update && apk add \
    alpine-base \
    libvirt-dev \
    abuild

WORKDIR /out

# Dump the hashes of the installed packages
RUN repro-get hash generate > SHA256SUMS

# Export the apks
RUN repro-get cache export repository-apk

# Sort the hashes
RUN sort -k2 -o SHA256SUMS SHA256SUMS

FROM scratch as output

COPY --from=builder /out/SHA256SUMS SHA256SUMS-apk-amd64
COPY --from=builder /out/repository-apk repository-apk
