// Code generated by "stringer -type=State"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Uninitialized-0]
	_ = x[AcceptingInit-1]
	_ = x[ActivatingNodes-2]
	_ = x[NodeWaitingForClusterJoin-3]
	_ = x[IsNode-4]
	_ = x[Failed-5]
	_ = x[maxState-6]
}

const _State_name = "UninitializedAcceptingInitActivatingNodesNodeWaitingForClusterJoinIsNodeFailedmaxState"

var _State_index = [...]uint8{0, 13, 26, 41, 66, 72, 78, 86}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
