/*
Copyright (c) Edgeless Systems GmbH

SPDX-License-Identifier: AGPL-3.0-only
*/

/*
Package cmd provides the Constellation CLI.

It is responsible for the interaction with the user.
*/
package cmd

import (
	"path/filepath"

	"github.com/edgelesssys/constellation/v2/internal/constants"
)

// Users may override the default workspace using the --workspace flag.
// The default workspace is the current working directory.
// The following functions return paths relative to the workspace.
// Packages outside of the cmd package should use paths generated by these functions.
// They must not use absolute paths, nor should they generate relative paths themselves.

func adminConfPath(workspace string) string {
	return filepath.Join(workspace, constants.AdminConfFilename)
}

func configPath(workspace string) string {
	return filepath.Join(workspace, constants.ConfigFilename)
}

func clusterIDsPath(workspace string) string {
	return filepath.Join(workspace, constants.ClusterIDsFilename)
}

func masterSecretPath(workspace string) string {
	return filepath.Join(workspace, constants.MasterSecretFilename)
}

func upgradeWorkspace(workspace string) string {
	return filepath.Join(workspace, constants.UpgradeDir)
}

func terraformClusterWorkspace(workspace string) string {
	return filepath.Join(workspace, constants.TerraformWorkingDir)
}

func terraformIAMWorkspace(workspace string) string {
	return filepath.Join(workspace, constants.TerraformIAMWorkingDir)
}

func terraformLogPath(workspace string) string {
	return filepath.Join(workspace, constants.TerraformLogFile)
}

const gcpServiceAccountKeyFile = "gcpServiceAccountKey.json"

func gcpServiceAccountKeyPath(workspace string) string {
	return filepath.Join(workspace, gcpServiceAccountKeyFile)
}
