#!/usr/bin/env bash
# Copyright (c) Edgeless Systems GmbH
#
# SPDX-License-Identifier: AGPL-3.0-only

# This script reads the PCR state of the system
# and prints the message to the serial console

main() {
  pcr_state="$(tpm2_pcrread sha256)"
  echo -e "PCR state:\n${pcr_state}\n" > /run/issue.d/35_constellation_pcrs.issue
}

main
