#!/usr/bin/env bash

set -euo pipefail
shopt -s inherit_errexit

pseudo_version() {
    if [[ -f "./.version.txt" ]]; then
        cat ./.version.txt
    else
        go run ./hack/pseudo-version
    fi
}

echo "STABLE_STAMP_COMMIT $(git rev-parse HEAD)"
echo "STABLE_STAMP_STATE $(git diff-index --quiet HEAD -- && echo "clean" || echo "dirty")"
echo "STABLE_STAMP_VERSION $(pseudo_version)"
echo "STABLE_STAMP_TIME $(go run ./hack/pseudo-version -print-timestamp -timestamp-format '2006-01-02T15:04:05Z07:00')"
